### PR TITLE
feat(docker): adds pluggable docker container

### PR DESCRIPTION
**Pull request by npepinpe**
**Description:**

This PR adds a Dockerfile which will create a small (~15MB) container image based on [busybox](https://hub.docker.com/_/busybox). The decision to base it on busybox is mostly for debugging purposes and being able to use a shell script as an entry point - we could consider making a separate busybox container to manipulate all "pluggable" exporters, and have exporters be purely data containers based on "scratch".

The final container contains the fat JAR under `/usr/share/zeebe/zeebe-hazelcast-exporter` and will be named after a configurable `EXPORTER_ID` argument (which is exported to the environment; defaults to `zeebe-hazelcast-exporter`). The exporter ID is used not only as the JAR name but also in the generated configuration. Right now this is done at build time, we could argue that this should be also done at container-creation time, so we might want to make the name static but allow changing what it will be copied to (which is already do-able using `SHARED_JAR` environment variable to point to the destination path).

Along with the image there is an `entrypoint.sh` shell script which on start will copy the exporter into a pre-defined (but customizable) shared directory (expected to be a shared volume), and will generate configuration from environment variables to be appended to a well known location (which for a deployment should also be a shared volume/location).

I also added a small `kubernetes.sample.yml` which starts a single broker and the exporter container as its `initContainer`. You can test it locally by deploying against your favorite local k8s setup (e.g. [kind](https://kind.sigs.k8s.io/)), and as far as I can tell it seems to work (maybe someone can test it properly :sweat_smile: - but the exporter is loaded and configured!).

There's also a small `Makefile` to ease building and pushing the docker images: I settled on `gcr.io/zeebe-io/zeebe-hazelcast-exporter` at the moment, I hope this wasn't used by someone else for an image which packages both Zeebe and the exporter :see_no_evil: 

Ping me if you have any question, I whipped this up in ~1h so I imagine we'll want to iterate on this.

### CODE REVIEW

**Comment by Zelldon** [comment]
What is the status here ? :D

**Comment by salaboy** [comment]
@Zelldon status is ... (drum roll) I am back from holidays :)

**Comment by Zelldon** [comment]
@saig0 do we still need this?

**Comment by saig0** [comment]
I think this is currently not so important.

**Pull request closed without merging**
